<?xml version="1.0" encoding="utf-8"?><Database Name="Preduzece" Class="PreduzecaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-DBN7H94\SQLEXPRESS;Initial Catalog=Preduzece;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PreduzeceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Kontakt" Member="Kontakts">
    <Type Name="Kontakt">
      <Column Name="KontaktID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ime" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prezime" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RadnoMesto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PreduzeceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kontakt_Mail" Member="Mails" ThisKey="KontaktID" OtherKey="KontaktID" Type="Mail" />
      <Association Name="Kontakt_Telefon" Member="Telefons" ThisKey="KontaktID" OtherKey="KontaktID" Type="Telefon" />
      <Association Name="Preduzece_Kontakt" Member="Preduzece" ThisKey="PreduzeceID" OtherKey="PreduzeceID" Type="Preduzece" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserRoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleID" OtherKey="RoleID" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mail" Member="Mails">
    <Type Name="Mail">
      <Column Name="MailAdresa" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OnakaTipa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KontaktID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kontakt_Mail" Member="Kontakt" ThisKey="KontaktID" OtherKey="KontaktID" Type="Kontakt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Preduzece" Member="Preduzeces">
    <Type Name="Preduzece">
      <Column Name="PreduzeceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Adresa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Opstina" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Postanskibroj" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PIB" Type="System.Decimal" DbType="Decimal(9,0) NOT NULL" CanBeNull="false" />
      <Column Name="SifraDelatnosti" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OpisDelatnosti" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BrRacuna" Type="System.Decimal" DbType="Decimal(13,0) NOT NULL" CanBeNull="false" />
      <Column Name="WebStr" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pecat" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Beleska" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Preduzece_Kontakt" Member="Kontakts" ThisKey="PreduzeceID" OtherKey="PreduzeceID" Type="Kontakt" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="RoleID" OtherKey="RoleID" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Telefon" Member="Telefons">
    <Type Name="Telefon">
      <Column Name="TelefonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OznakaTipa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BrojTelefona" Type="System.Decimal" DbType="Decimal(7,0) NOT NULL" CanBeNull="false" />
      <Column Name="Lokal" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KontaktID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kontakt_Telefon" Member="Kontakt" ThisKey="KontaktID" OtherKey="KontaktID" Type="Kontakt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="UserID" OtherKey="UserID" Type="UserRole" />
    </Type>
  </Table>
</Database>